DOMAIN-KEYWORD,microsoft,DIRECT
DOMAIN-SUFFIX,aaplimg.com,DIRECT
DOMAIN-SUFFIX,akadns.net,DIRECT
DOMAIN-SUFFIX,akamaiedge.net,DIRECT
DOMAIN-SUFFIX,android.clients.google.com,DIRECT
DOMAIN-SUFFIX,apple-cloudkit.com,DIRECT
DOMAIN-SUFFIX,apple-dns.net,DIRECT
DOMAIN-SUFFIX,apple-mapkit.com,DIRECT
DOMAIN-SUFFIX,apple.com,DIRECT
DOMAIN-SUFFIX,beacons.gcp.gvt2.com,DIRECT
DOMAIN-SUFFIX,beacons.gvt2.com,DIRECT
DOMAIN-SUFFIX,beacons3.gvt2.com,DIRECT
DOMAIN-SUFFIX,cdn-apple.com,DIRECT
DOMAIN-SUFFIX,cdn20.com,DIRECT
DOMAIN-SUFFIX,clientservices.googleapis.com,DIRECT
DOMAIN-SUFFIX,connectivitycheck.gstatic.com,DIRECT
DOMAIN-SUFFIX,csi.gstatic.com,DIRECT
DOMAIN-SUFFIX,dl.google.com,DIRECT
DOMAIN-SUFFIX,edgekey.net,DIRECT
DOMAIN-SUFFIX,fonts.googleapis.com,DIRECT
DOMAIN-SUFFIX,fonts.gstatic.com,DIRECT
DOMAIN-SUFFIX,gfx.ms,DIRECT
DOMAIN-SUFFIX,google.cn,DIRECT
DOMAIN-SUFFIX,icloud-content.com,DIRECT
DOMAIN-SUFFIX,icloud.com,DIRECT
DOMAIN-SUFFIX,images-cn.ssl-images-amazon.com,DIRECT
DOMAIN-SUFFIX,login.live.com,DIRECT
DOMAIN-SUFFIX,me.com,DIRECT
DOMAIN-SUFFIX,msauth.net,DIRECT
DOMAIN-SUFFIX,msecnd.net,DIRECT
DOMAIN-SUFFIX,msedge.net,DIRECT
DOMAIN-SUFFIX,msocdn.com,DIRECT
DOMAIN-SUFFIX,mwcloudcdn.com,DIRECT
DOMAIN-SUFFIX,mwcname.com,DIRECT
DOMAIN-SUFFIX,mzstatic.com,DIRECT
DOMAIN-SUFFIX,office.com,DIRECT
DOMAIN-SUFFIX,onestore.ms,DIRECT
DOMAIN-SUFFIX,redirector.gvt1.com,DIRECT
DOMAIN-SUFFIX,safebrowsing-cache.google.com,DIRECT
DOMAIN-SUFFIX,safebrowsing.googleapis.com,DIRECT
DOMAIN-SUFFIX,ssl.gstatic.com,DIRECT
DOMAIN-SUFFIX,storage.live.com,DIRECT
DOMAIN-SUFFIX,translate.googleapis.com,DIRECT
DOMAIN-SUFFIX,update.googleapis.com,DIRECT
DOMAIN-SUFFIX,windows.com,DIRECT
DOMAIN-SUFFIX,windows.net,DIRECT
DOMAIN-SUFFIX,windowsupdate.com,DIRECT
DOMAIN-SUFFIX,www.gstatic.com,DIRECT
DOMAIN-SUFFIX,xboxlive.com,DIRECT