DOMAIN-KEYWORD,adservice.google,REJECT
DOMAIN-KEYWORD,amazon-adsystem,REJECT
DOMAIN-KEYWORD,associates-amazon,REJECT
DOMAIN-KEYWORD,collector.githubapp,REJECT
DOMAIN-KEYWORD,crashlytics,REJECT
DOMAIN-KEYWORD,dm.toutiao,REJECT
DOMAIN-KEYWORD,doubleclick.net,REJECT
DOMAIN-KEYWORD,google-analytics,REJECT
DOMAIN-KEYWORD,googleadservices,REJECT
DOMAIN-KEYWORD,googleanalytics,REJECT
DOMAIN-KEYWORD,googlesyndication,REJECT
DOMAIN-KEYWORD,googletagmanager,REJECT
DOMAIN-KEYWORD,googletagservices,REJECT
DOMAIN-KEYWORD,hectorstatic.baidu,REJECT
DOMAIN-KEYWORD,hm.baidu,REJECT
DOMAIN-KEYWORD,pangolin-sdk-toutiao,REJECT
DOMAIN-KEYWORD,taboola,REJECT
DOMAIN-KEYWORD,tracking.epicgames,REJECT
DOMAIN-KEYWORD,umengcloud,REJECT
DOMAIN-KEYWORD,ut.taobao,REJECT